version: '3'

services:
    bandersnatch:
        build: './bandersnatch'
        volumes:
            - pypi-volume:/data
    nginx:
        build: './nginx'
        ports:
            - "8080:80"
        links:
            - bandersnatch
        volumes:
            - pypi-volume:/data:ro

volumes:
    pypi-volume: